name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)
variables:
  CI_NAME: Azure Pipelines
  CI_BUILD_ID: $(Build.BuildId)
  CI_BUILD_URL: "https://dev.azure.com/samaloney/xrayvision/_build/results?buildId=$(Build.BuildId)"
  CIBW_BUILD: cp310-* cp311-* cp312-*
  CIBW_SKIP: "*-win32 *-manylinux1_i686"

resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: samaloney
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

trigger:
  branches:
    include:
    - '*'
    exclude:
    - '*backport*'
  tags:
    include:
    - 'v*'
    exclude:
    - '*dev*'
    - '*pre*'
    - '*post*'

jobs:
- template: run-tox-env.yml@OpenAstronomy
  parameters:
    submodules: false
    coverage: codecov
    envs:
      - linux: codestyle
        name: codestyle

      - linux: py39
        name: py39_linux_test

      - linux: py310
        name: py310_linux_test

      - linux: py311
        name: py311_linux_test

      - linux: py312
        name: py312_linux_test

      - macos: py39
        name: py39_mac_test
        coverage: false

      - macos: py310
        name: py310_mac_test
        coverage: false

      - macos: py311
        name: py311_mac_test
        coverage: false

      - macos: py312
        name: py312_mac_test
        coverage: false

      - windows: py39
        name: py39_win_test

      - windows: py310
        name: py310_win_test

      - windows: py311
        name: py311_win_test

      - windows: py312
        name: py312_win_test

# On branches which aren't master, and not Pull Requests, build the wheels but only upload them on tags
- ${{ if and(ne(variables['Build.Reason'], 'PullRequest'), not(contains(variables['Build.SourceBranch'], 'master'))) }}:
  - template: publish.yml@OpenAstronomy
    parameters:
      # Only Upload to PyPI on tags
      ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
        pypi_connection_name : 'pypi'

      test_extras: 'all,test'
      test_command: 'pytest -p no:warnings --doctest-rst -m "not figure" --pyargs xrayvision'
      submodules: false
      targets:
        - wheels_universal
        - sdist
      dependsOn:
        - py39_linux_test
        - py310_linux_test
        - py311_linux_test
        - py312_linux_test
        - py39_mac_test
        - py310_mac_test
        - py311_mac_test
        - py312_mac_test
        - py39_win_test
        - py310_win_test
        - py311_win_test
        - py312_win_test
